reactioncommerce/reaction-component-library

README.md

The git URL in the getting started guide now points to the right repo.

Fix git clone URL in README

---

.reaction/scripts/addcomponent.js

The addcomponent script was still pointing to the old components directory and would either error or create a component in the wrong place.
Updated the script's output path from `src/components` to `package/sc/components`
Run `docker-compose up --build` to start the RC component lib
Run `docker-compose run --rm web node .reaction/scripts/addcomponent {component name}`
The new component should be added to the `package/src/components`

(fix): addcomponent script correct component path

---

package.json
package/src/components/Price/v1/Price.js
package/src/components/Price/v1/Price.md
package/src/components/Price/v1/Price.test.js
package/src/components/Price/v1/__snapshots__/Price.test.js.snap
package/src/components/Price/v1/index.js
package/src/defaultComponentTheme.js
styleguide.config.js
styleguide/src/sections/Product.md
yarn.lock

This component renders the price of the item in a cart. If there is a difference between the price of the item and the "compare at" price or "MSRP" price, the cart item price should indicate the comparable price crossed out and show the actual price below it.
Reference connected issue https://github.com/reactioncommerce/reaction-next-starterkit/issues/137 for more details.

Add Price component.

---

package/package.json

Updates the GitHub repository link in https://www.npmjs.com/package/@reactioncommerce/components. The https://www.npmjs.com/package/@reactioncommerce/components's GitHub.com link currently goes to a broken link.

chore(package.json): fix github repository and homepage link

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/component_request.md
.github/pull_request_template.md

Resolves #91  
PR and issues formats are not standardized.
- Add a `pull_request_template.md` file in `.github` folder to create a PR template
- Add 2 issue request templates in `ISSUE_TEMPLATE` folder for a component request, and for bug reports
- ⚠️:  📦🚀Adds a note about semantic release on the PR template so people are alerted!

chore(github): add PR template, bug report template, component request template

---

.github/pull_request_template.md
docs/README.md
docs/reviewing-components.md

Resolves #105   
Type: **docs**
- Add a link to the Component issue template
- Add 2 things to the PR template: Does this component require other components? Does this component add any NPM dependencies?
- Add a Component Review doc that goes over how a Component PR review should be checked off by Design, Dev and Doc before publishing.
1. Read the [docs](https://github.com/reactioncommerce/reaction-component-library/tree/105-machikoyasuda-docs-process/docs), with particular attention to [Component review process](https://github.com/reactioncommerce/reaction-component-library/blob/105-machikoyasuda-docs-process/docs/reviewing-components.md)
2. Does it make sense? Leave a comment with your thoughts below ⬇️

docs: document process

---

styleguide.config.js

`tldr`: The Markdown code blocks are hard to read. This is a temporary bug fix to change the Markdown code backgrounds back to a light grey, to match the syntax highlighting style React Styleguidist (RSG) uses.
`the long story`: RSG uses highlight.js to highlight the Markdown code blocks, and also uses CodeMirror for all the code blocks in the Component section. The CodeMirror theme is configurable in `styleguide.config.js`*, but the Markdown theme is _not_. The Markdown highlight.js theme is hardcoded in their component here: https://github.com/styleguidist/react-styleguidist/blob/66be5011eb773d0107fea9d8e054968a737b5574/src/rsg-components/Markdown/Markdown.js#L18 at `tomorrow.css` which gets injected as inline-css on all pages:
This is the theme …

style bug: make markdown code snippets readable

---

package/src/components/Select/v1/Select.js

Resolves #134 
You can now change the value of the Select when it has an initial `value` prop. Also set zIndex of menu to fix issues with display on Style Guide.
NONE
Verify that you can change the value of the Select in the last example on the Select style guide page.

fix(select): allow initial value to change

---

.gitignore
README.md
styleguide.config.js

Issue: #145 
Impact: **major**  -  because it changes the way we deploy and release
I'd like to be able to run `styleguide:build` locally to make sure it's working, make sure the build looks correct, without triggering Git. We have a few files that _are_ required in `styleguide/src`, so I want to selectively gitignore all of the other files. Instead of doing this by adding it to the gitignore, I am:
- Changing the `styleguide:build` output directory to `dist`. This directory is already gitignored.
- Now that this PR is already being preview-branch-deployed, the build directory will be changed from `styleguide/` to `styleguide/dist`.
Now when you run `styleguide:build`, the app is built into `styleguide/dist`:
```sh
$ docker-compose run --rm web yarn run styleguide:build …
```

chore(deployment): build styleguide in styleguide/dist folder

---

.reaction/scripts/addcomponent.js
package/src/components/Button/v1/Button.md
package/src/components/CartEmptyMessage/v1/CartEmptyMessage.md
package/src/components/CartItem/v1/CartItem.md
package/src/components/CartItemDetail/v1/CartItemDetail.md
package/src/components/CartItems/v1/CartItems.md
package/src/components/CartSummary/v1/CartSummary.md
package/src/components/Checkbox/v1/Checkbox.md
package/src/components/CheckoutAction/v1/CheckoutAction.md
package/src/components/CheckoutActionComplete/v1/CheckoutActionComplete.md
package/src/components/CheckoutActionIncomplete/v1/CheckoutActionIncomplete.md
package/src/components/CheckoutEmailAddress/v1/CheckoutEmailAddress.md
package/src/components/CheckoutTopHat/v1/CheckoutTopHat.md
package/src/components/ErrorsBlock/v1/ErrorsBlock.md
package/src/components/Field/v1/Field.md
package/src/components/MiniCart/v1/MiniCart.md
package/src/components/MiniCartSummary/v1/MiniCartSummary.md
package/src/components/Price/v1/Price.md
package/src/components/QuantityInput/v1/QuantityInput.md
package/src/components/Select/v1/Select.md
package/src/components/ShopLogo/v1/ShopLogo.md
package/src/components/StockWarning/v1/StockWarning.md
package/src/components/TextInput/v1/TextInput.md
styleguide.config.js
styleguide/src/styles.css

Resolves #146
Type: **docs**
- Docs: Adds `### Overview` and `#### Usage` to all pages
- Docs: Reorganizes sidebar and adds a MiniCart section
- Chore: Changes the `addcomponent` script to make a new Markdown file with this template:
```
```
Docs look all better!
no
1. run `docker-compose run --rm web node .reaction/scripts/addcomponent MyComponentNew`
2. Check the template to see if it matches:
```
```

docs(#146): backfill docs with sections

---

styleguide.config.js

Resolves #169  
Make the text measure 60% for paragraphs, unordered lists and ordered lists.

style: make paragraph, list width 60%

---

package/src/components/MiniCart/v1/MiniCart.js
package/src/components/MiniCart/v1/MiniCart.md
package/src/components/MiniCart/v1/MiniCart.test.js

Resolves #173
Impact: **minor** 
- Updates `subtotal` and `tax` to match their new names in the GraphQL Cart schema, `itemTotal` and `taxTotal`.
Include mobile and desktop screenshots.
Changes some prop names, but this is the first time the component is being used on the `reaction-next-starterkit` so there's no need to make a copy.
1. Verify the component renders in docs

refactor: update cart.checkout.summary props in MiniCart

---

package/src/components/MiniCartSummary/v1/MiniCartSummary.js

Resolves #167 
The MIniCartSummary component did not have a `font-family` attached to it. Locally in the component library, it was displaying correctly as the whole library is the correct font, however, when it was imported into the starterkit, the font was incorrect.
MiniCartSummary
none.
1. See the the font is updated in the component library
1. Link this PR's version of the component library to the starterkit: [Instructions](https://github.com/reactioncommerce/reaction-next-starterkit/pull/199)
1. Start up starterkit locally following the instructions linked above
1. Hover over the cart icon on starterkit
1. See that the `MiniCartSummary` area has the correct font

fix: add font-family to component

---

package/src/components/MiniCartSummary/v1/__snapshots__/MiniCartSummary.test.js.snap
package/src/components/QuantityInput/v1/QuantityInput.js
package/src/components/QuantityInput/v1/__snapshots__/QuantityInput.test.js.snap

Resolves #157 
Type: **bugfix|style**
- Remove ripple and touchRipple from buttons on QuantityInput
1. Test + and - button on Mobile, Desktop, Firefox, Chrome
More detail for what each of these sections should include are available in our [Contributing Docs](https://docs.reactioncommerce.com/reaction-docs/master/contributing-to-reaction)

fix(quantityinput): disable ripple, touchripple from buttons

---

package/src/components/PhoneNumberInput/v1/PhoneNumberInput.js
package/src/components/PhoneNumberInput/v1/__snapshots__/PhoneNumberInput.test.js.snap

Resolves #191 
- PhoneNumberInput in Firefox
none
1. Test PhoneNumberInput in Firefox
2. Test AddressBook's PhoneNumberInput in Firefox

fix(phonenumberinput): add height/width to size clear button

---

package/src/components/PhoneNumberInput/v1/PhoneNumberInput.js

Resolves #193 
The PhoneNumberInput needed `isFormInput` property added to it's`withComponents` context wrapper.
1. Go to the bottom of the AddressForm page, fill out and submit the form.
2. You should see the address in the console and no validation error on the phone field.

fix: updated PhoneNumberInput wrapper context

---

package/src/components/AddressForm/v1/AddressForm.js
package/src/components/ErrorsBlock/v1/ErrorsBlock.md
package/src/components/Field/v1/Field.md
package/src/components/Field/v1/__snapshots__/Field.test.js.snap
package/src/components/PhoneNumberInput/v1/PhoneNumberInput.js
package/src/components/PhoneNumberInput/v1/__snapshots__/PhoneNumberInput.test.js.snap
package/src/components/Select/v1/Select.js
package/src/components/TextInput/v1/TextInput.js
package/src/components/TextInput/v1/__snapshots__/TextInput.test.js.snap

Resolves #192 
- TextInput, PhoneNumberInput, and Select now accept and pass along an `id` prop
- AddressForm uses the above change to add `id` and `for` to HTML for accessibility. Clicking the labels on that form no focuses the related input. (This doesn't seem to work with react-select package, but that would be an issue for them to fix.)
- The Field and ErrorsBlock markdown examples now show proper use of id/labelFor props
None
Verify the changes and that the linked issue is fixed.
- https://deploy-preview-202--stoic-hodgkin-c0179e.netlify.com/#!/Field
- https://deploy-preview-202--stoic-hodgkin-c0179e.netlify.com/#!/PhoneNumberInput
- https://deploy-preview-202--stoic-hodgkin-c0179e.netlify.com/#!/ErrorsBlock
- …

Labels accessibility fix

---

package/package.json
package/src/components/CartEmptyMessage/v1/CartEmptyMessage.js
package/src/components/CartEmptyMessage/v1/__snapshots__/CartEmptyMessage.test.js.snap
package/src/components/MiniCartSummary/v1/__snapshots__/MiniCartSummary.test.js.snap
package/src/defaultComponentTheme.js

Related to https://github.com/reactioncommerce/reaction-next-starterkit/issues/207
1. Follow [these instructions](https://github.com/reactioncommerce/reaction-next-starterkit#testing-reaction-component-library-components-in-the-starterkit) to get this version of the Component Library in the starterkit
1. Start the `fix-207-kieckhafer-emptyCartMessage` branch of the starterkit (or master if https://github.com/reactioncommerce/reaction-next-starterkit/pull/220 is merged)
1. See that the correct font is used for the Cart Empty Message text

add font-family to CartEmptyMessage style

---

package.json
styleguide.config.js
styleguide/src/appComponents.js

Resolves #207 
Added [babl-poyfill](https://babeljs.io/docs/en/babel-polyfill/) to styleguide for IE11 support.
1. Start the component lib and view it in IE11
2. Component pages should now be loading

fix: added babel-polyfill to fix IE11 support

---

package.json
package/src/components/Link/v1/Link.js
package/src/components/Link/v1/Link.md
package/src/components/Link/v1/Link.test.js
package/src/components/Link/v1/__snapshots__/Link.test.js.snap
package/src/components/Link/v1/index.js
styleguide.config.js

Resolves #212 
This PR adds a simple Link component to the library.
Image link:
Text link:
None
1. Confirm component appears under Base Components -> Actions in docs
2. Text link w/ no onClick handler - confirm it brings you to google.com
3. Test link w/ image & onClick handler - confirm it shows an alert

#212: Create Link component

---

package/src/components/CartSummary/v1/CartSummary.js
package/src/components/CartSummary/v1/CartSummary.md
package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap

Resolves #214
New design: https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5ada4347eda5814422ce39e2
- Update line-item labels. 
- `Subtotal` => `Item total`
- `Total` => `Order total`
- Add borders around `Order total` row
- Add an option for a dense layout with a transparent background
none
1. Open the docs to the CartSummary component docs
2. See the updates mentioned in the `Component` section

feat: Cart summary style updates and dense layout

---

package/src/components/Checkbox/v1/Checkbox.js
package/src/components/Checkbox/v1/Checkbox.md
package/src/components/Checkbox/v1/__snapshots__/Checkbox.test.js.snap
package/src/components/Checkbox/v1/index.js
package/src/defaultComponentTheme.js
styleguide.config.js

When I pulled the Checkbox into the Reaction Meteor app, it did not display correctly. This was mostly due to using `rems`. I've switched it to using ems and pixels as appropriate. For most values, em makes sense because as the font size of the checkbox label increases, it looks best if the checkbox increases proportionally.
Also adds `isFormInput = true` static property on `Checkbox`. Without this, it does not work correctly within a ReactoForm form.
None
Verify that the Checkbox component looks good in various browsers and if you play with the `font-size` of the label and the `html` root, everything continues to look good.

fix: checkbox style fixes

---

package/src/components/MiniCart/v1/MiniCart.js
package/src/components/MiniCart/v1/MiniCart.md

Resolves #232
Type: **bugfix/feature**
Add event prop `onCheckoutButtonClick` for the supplied checkout button in the MiniCart component. This will allow you to add an event to the default button without having to supply your own.
none
1. Open the docs to the MiniCart page
2. Click the checkout button
3. See the alert

bug: add minicart checkout button `onCheckoutButtonClick` event

---

styleguide.config.js

Resolves #236
- Updated style for mobile and tablet-width viewing
- On mobile, the long name of a component will be hyphenated
- On mobile, the x-axis should not scroll
- On tablet, the sidebar should be shown at the bottom
1. Check at 50% width on desktop
2. Check on mobile device
3. Test a component with a long name

style(mobile): #236 - improve mobile design

---

package/src/components/Field/v1/__snapshots__/Field.test.js.snap
package/src/components/PhoneNumberInput/v1/__snapshots__/PhoneNumberInput.test.js.snap
package/src/components/Select/v1/Select.js
package/src/components/Select/v1/__snapshots__/Select.test.js.snap
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/ShippingAddressCheckoutAction/v1/__snapshots__/ShippingAddressCheckoutAction.test.js.snap
package/src/components/TextInput/v1/__snapshots__/TextInput.test.js.snap
package/src/defaultComponentTheme.js

Resolves #241 
The TextInput, Select and ShippingAddressCheckoutAction all had been inheriting their font-family from the `body`. This would cause a serif text to render when using these components in the storefront.
1. Visit the TextInput, Select and ShippingAddressCheckoutAction, verify that "source sans" is being used by all text elements.

fix: nnnnat 241 fixed font family on form/checkout action elements

---

package/src/components/AddressForm/v1/AddressForm.js
package/src/components/AddressForm/v1/AddressForm.md
package/src/components/AddressForm/v1/__snapshots__/AddressForm.test.js.snap
package/src/tests/mockComponents.js
styleguide/src/appComponents.js
styleguide/src/sections/InstallingandImporting.md

Resolves #234 
Added a `Checkbox` field for `isCommercial` property.
N/A
1. At the bottom of the `AddressForm` page add `shouldShowIsCommercialField` prop to the `AddressForm` inside the implementation example editor.
2. The "Is a commercial address" field should appear, select the checkbox and submit the form
3. In the browser console, you should see the address object from the form with an `isCommercial` property set to `true`.

Feat 234 nnnnat commercial field

---

package/src/components/CatalogGrid/v1/CatalogGrid.js
package/src/components/CatalogGrid/v1/CatalogGrid.md
package/src/components/CatalogGridItem/v1/CatalogGridItem.js

Resolves #247 
Added an `onItemClick` prop to CatalogGrid, `onClick` prop to CatalogItem, and passed that as the link's click handler. Result: When a user clicks on an item in the grid, `onItemClick` is fired.
N/A (UI doesn't change)
None
1. Click on items in the first example grid.
2. Confirm nothing happens (`event.preventDefault` is called in the example code).
3. Confirm other examples link to /product/SLUG (even though 404 in component lib)

feat: add item click handler prop to CatalogGrid

---

package/src/components/AddressForm/v1/AddressForm.js
package/src/components/AddressForm/v1/AddressForm.md
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.md

Resolves #229 
Added an optional text field that can capture an "Address Name" to the `AddressForm`.
N/A
1. On staging go to the bottom of the `AddressForm` docs and add `shouldShowAddressNameField` prop to the `<AddressForm />` in the example implementation editor.
2. Fill out the `AddressForm` with an "Address Name" and submit the form.
3. In the browser console, you should see the address object with the `addressName` property.
@aldeed  I tagged you as a reviewer just to verify my address property name "addressName" would be OK.

(feat): added addressName optional field to AddressForm

---

package/src/components/CheckoutEmailAddress/v1/CheckoutEmailAddress.js
package/src/components/CheckoutEmailAddress/v1/__snapshots__/CheckoutEmailAddress.test.js.snap

Resolves N/A
Type: **feature|bugfix**
Updated `CheckoutEmailAddress` CSS to encapsulate more styles into the component and not make the consuming app responsible for the padding and border.
[design](https://zpl.io/2y7D0Nn)
N/A
1. Make sure the CheckoutEmailAddress component looks like the design.

(fix): nnnnat updated CheckoutEmailAddress styles

---

package/src/components/CheckoutActions/v1/CheckoutActions.md
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js

Impact: minor
Type: fix
Wiresup the `StripeForm` component to collect billing address
1. Run component library locally
2. Add a console.log(payment) here: https://github.com/reactioncommerce/reaction-component-library/compare/feat-willopez-wireup-billing-address-in-stripe-form?expand=1#diff-28d16de18ab7ee6a9975f2f042a7428cL124
3. In CheckoutActions complete step 1 and then 2, on the step 2 click on "Use different billing address" and fill out form.
4. Submit form
5. Verify the console log outputs the entered billing address

Wireup StripeForm to collect billing address

---

package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js

Impact: Minor
Type: Bug
Removes unnecessary lifecycle method that sets the component to "Not Ready for Save" state by default, without considering already set values.

fix: remove unnecessary lifecycle method

---

package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.js

Impact: minor
Type: bug
It's necessary to clone fulfillment options before sorting, due to the fact the Apollo Client uses immutable Objects
1. Verify that the most inexpensive shipping option is selected by default in `CheckoutActions`

fix: clone fulfillment options before sorting

---

package/src/components/CheckoutActions/v1/CheckoutActions.js
package/src/components/CheckoutActions/v1/__snapshots__/CheckoutActions.test.js.snap

Impact: minor
Type: fix
Removes the bottom border for the last `CheckoutAction`, so that it matches designs.
Testing; 
Verify bottom border for last `CheckoutAction` is not rendered.

fix: removes the bottom border from the last CheckoutAction

---

package/src/components/ShopLogo/v1/ShopLogo.md
package/src/components/ShopLogo/v1/ShopLogo.test.js
package/src/components/ShopLogo/v1/__snapshots__/ShopLogo.test.js.snap

Resolves #278
Updates `ShopLogo` markdown, tests, and snapshot to remove the `http` protocol from the source for the placehold.it image.
`http://placehold.it/60` => `//placehold.it/60` so that we're not loading an insecure resource.
1. Visit the preview link for the `ShopLogo` component: https://deploy-preview-279--stoic-hodgkin-c0179e.netlify.com/#!/ShopLogo
2. Ensure that the image is being loaded over https and that there are no https warnings.
3. Ensure that the image is visible

fix: remove insecure http protocol from placehold.it src

---

package/src/components/CatalogGrid/v1/CatalogGrid.js

Resolves #282 
Add `initialSize` prop to `CatalogGrid` to be passed down to the [container-query](https://github.com/d6u/react-container-query) component.
N/A
1. Spin up Styleguide and navigate to the [CatalogGrid](https://stoic-hodgkin-c0179e.netlify.com/#!/CatalogGrid) page
3. Using React Devtools inspect the ContainerQuery component and verify the `initailSize` prop is set to `{ width: 325 }`

feat: added initailSize prop for SSR

---

package/src/components/CartSummary/v1/CartSummary.js
package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap
package/src/components/MiniCartSummary/v1/MiniCartSummary.js
package/src/components/MiniCartSummary/v1/__snapshots__/MiniCartSummary.test.js.snap

Resolves #287 
Type: **bugfix|style**
- MiniCartSummary: Update font color of left-hand side labels
- CartSummary: Update font color of left-hand side labels
1. https://deploy-preview-290--stoic-hodgkin-c0179e.netlify.com/#!/MiniCartSummary
2. https://deploy-preview-290--stoic-hodgkin-c0179e.netlify.com/#!/CartSummary

fix(287): update font color in cart summary, minicart summary

---

package/src/components/ViewerInfo/v1/ViewerInfo.js
package/src/components/ViewerInfo/v1/ViewerInfo.md
package/src/components/ViewerInfo/v1/ViewerInfo.test.js
package/src/components/ViewerInfo/v1/__snapshots__/ViewerInfo.test.js.snap
package/src/defaultComponentTheme.js

Resolves #283 
Type: **bugfix|refactor**
* Guard against null/undef `viewer` props.
* Updated to only show the initial on mobile devices.
* Updated test
N/A
1. Load the compo-lib and navigate to the ViewerInfo page.
2. size the browser down or use responsive design view to see the component render only the initial for the small screen size.
3. Remove the `viewer` prop from the component example and see the page no-longer throws an error.

fix: 283 nnnnat viewerinfo

---

package/src/components/ViewerInfo/v1/ViewerInfo.js
package/src/components/ViewerInfo/v1/ViewerInfo.md
package/src/components/ViewerInfo/v1/ViewerInfo.test.js
package/src/components/ViewerInfo/v1/__snapshots__/ViewerInfo.test.js.snap

Resolves #291
`ViewerInfo` component would throw an error if it received a `viewer` object that was missing a `firstName` prop. 
`ViewerInfo` now expects `primaryEmailAddress` to always be available on the `viewer` object and will use the viewer's email address in place of `firstName`.
N/A
1. Verify `ViewerInfo` will not throw an error if missing the `firstName` prop.

refactor: nnnnat viewerinfo

---

package/src/components/CheckoutActions/v1/CheckoutActions.js
package/src/components/CheckoutActions/v1/CheckoutActions.md

Impact: minor
Type: refactor
Removes an unnecessary re-render triggered by `forceUpdate`, this caused the stripe payment action to become active when the user clicked on the place your order button.
Further, the example code was cleanup.
1.  Visit the `CheckoutActions` component
2. Verify steps 1-4 work as expected.

Fix checkout actions: remove unnecessary re-render

---

package/src/components/CatalogGridItem/v1/CatalogGridItem.js

Resolves #324 from Starterkit: https://github.com/reactioncommerce/reaction-next-starterkit/issues/324
When a `CatalogGridItem` is updated with a new product, if the previous product's images were landscape, and the new images were portrait (or vice-versa), the `fit` prop on `ProgressiveImage` wasn't being updated. This caused portrait images to have the original bug where white bars appeared to the left & right of the image.
This PR fixes that by updating the image fit via `componentDidUpdate`. I was only able to confirm it in the component lib markdown example by temporarily moving `this.props.product` to `this.state.product` and using a `setTimeout` to change the product after 10s. Unfortunately the only way to fully confirm the fix is to merge this …

fix: update catalog item's image fit on component update

---

package/src/components/Select/v1/Select.js
package/src/components/Select/v1/Select.md
package/src/defaultComponentTheme.js

Resolves #286 
Type: **bugfix|style**
The issue & solution -- It appeared as though when using <kbd>^</kbd> or <kbd>V</kbd> to navigate through Select options, nothing was happening. But actually, the option was being selected/focused, but the user couldn't tell because the option wasn't changing colors. The solution is to add a background color to the option that changes by the option's state: selected or hovered/focused.
- Fix: Adds `getSelectedBackgroundColor()` of `#d6e5ed` - Once a user selects an option, and then opens the Select again, the selected option will have a darker background color.
- Fix: Adds `getSelectHoverColor()` of `#ecf8fe` to any option that is focused with the keyboard <kbd>^</kbd> or <kbd>V</kbd>, in addition to options that are hovered with …

fix(select): add background color for Selected and Focused options

---

package/src/components/CatalogGridItem/v1/CatalogGridItem.js

Resolves #302 
I introduced an infinite loop into `CatalogGridItem`. When the component is updated with a new product, the goal was to have the image `fit` prop for the child `ProgressiveImage` component to be determined automatically, based on whether the image is landscape or portrait. By not checking whether the new calculated fit differed from the previous, `this.setState` and thus `componentDidUpdate` were being called infinitely.
The solution was to check whether the new calculated fit differed from the previous.
1. Add a `console.log` to `componentDidUpdate` inside CatalogGridItem.js
2. Visit the Catalog Grid page in the component lib docs
3. Confirm `console.log` only prints once per product on the screen.

fix: prevent infinite loop when setting image size in CatalogGridItem

---

package/src/components/TextInput/v1/TextInput.js

Resolves #270 
Impact: minor
Type: bugfix
###
Remove input focus after user clicks on clear button, and when the user clicks away from the input.
1. Enter text into TextInput component
2. Click away from component
3. Verify green focus ring is not present.
4. Click on the input
5. Click on the clear button
6. Verify green input ring is not present and that text was cleared.

fix: do not focus input after user clicks the clear button

---

package/src/components/AddressForm/v1/AddressForm.js
package/src/components/Select/v1/Select.js
package/src/components/Select/v1/Select.md
package/src/components/Select/v1/Select.test.js
package/src/components/Select/v1/__snapshots__/Select.test.js.snap

Resolves [#322](https://github.com/reactioncommerce/reaction-next-starterkit/issues/322)
Type: **feature|bugfix**
The`AddressForm` component is using a locales dataset that is ordered by the country code, this causes the option's labels to not be alphabetized in the `Select`. 
* Add `alphabetize` prop to the `Select` component that will sort the provided options by the label.
* Added the `alphabetize` prop to all `Select` components in `AddressForm`
N/A
1. Visit the `Select` [page's](https://deploy-preview-305--stoic-hodgkin-c0179e.netlify.com/#!/Select) new "Alphabetizing select options` section and verify it's sorting the options correctly.
2. Visit the `AddressForm` [page](https://deploy-preview-305--stoic-hodgkin-c0179e.netlify.com/#!/AddressForm) and verify all …

fix: 322 nnnnat abc select

---

package.json
styleguide.config.js
yarn.lock

When going to the style guide URL and looking in browser or server console, you would see this warning:
```
webpackHotDevClient.js:138 ./styleguide/src/components/README.md
Module parse failed: Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
| Put components in this folder if they're used only by the style guide itself or required by code examples in Component.md files, but not part of the published component library.
```
After adding the `ignore-loader` package as a dev dependency and configuring `README.md` files to use that loader, the warning no longer appears.
Run the style guide locally and verify that the "Module parse failed" error does not appear in the browser console.

fix: ignore README.md file in /styleguide/src/components

---

.reaction/scripts/addcomponent.js
.reaction/scripts/templates/Component.js.template
docs/component-development-guidelines.md
package/src/components/AddressForm/v1/AddressForm.js
package/src/components/Button/v1/Button.js
package/src/components/CartEmptyMessage/v1/CartEmptyMessage.js
package/src/components/CartItem/v1/CartItem.js
package/src/components/CartItems/v1/CartItems.js
package/src/components/CatalogGrid/v1/CatalogGrid.js
package/src/components/CatalogGridItem/v1/CatalogGridItem.js
package/src/components/CheckoutActionComplete/v1/CheckoutActionComplete.js
package/src/components/CheckoutActions/v1/CheckoutActions.js
package/src/components/ErrorsBlock/v1/ErrorsBlock.js
package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.js
package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.js
package/src/components/GuestForm/v1/GuestForm.js
package/src/components/MiniCart/v1/MiniCart.js
package/src/components/PhoneNumberInput/v1/PhoneNumberInput.js
package/src/components/SelectableList/v1/SelectableList.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/StripeForm/v1/StripeForm.js
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js
package/src/components/TextInput/v1/TextInput.js

Resolves #245
Updates the `addcomponent` script's component template.
- Includes `className` prop type and passes it along to the outermost DOM element. (#245)
- Includes `components` prop because it's a common requirement
- Uses `applyTheme` rather than a hard-coded color value to encourage proper theme-ability of components.
1. Run `docker-compose run --rm web node .reaction/scripts/addcomponent SomeNewComponent`
2. Verify that the component files generated look good and have all of the mentioned changes.

chore: updates to addcomponent script

---

docs/creating-new-component.md

Resolves #261 
Type: **docs**
The docs do not tell users to install node packages before creating components.

docs: added a `yarn` command before creating a new component.

---

package/src/components/CheckoutAction/v1/CheckoutAction.js
package/src/components/CheckoutAction/v1/CheckoutAction.md
package/src/components/CheckoutAction/v1/CheckoutAction.test.js
package/src/components/CheckoutAction/v1/__snapshots__/CheckoutAction.test.js.snap
package/src/components/CheckoutActions/v1/CheckoutActions.js
package/src/components/CheckoutActions/v1/CheckoutActions.md
package/src/components/CheckoutActions/v1/CheckoutActions.test.js

Resolves #265 
Type: **feature|refactor**
`CheckoutActions` needed a way to display different labels by "status". 
* `CheckoutAction` now accepts a `activeLabel, completeLabel, incompleteLabel` to show different labels durring each "status".
* `CheckoutActions` now expects these "status" labels from each `props.action` and passes them down to the `CheckoutAction` component.
The `CheckoutActions` component now requires each `action` object to:
* include each "status" label.
* include a unique `_id`.
1. Verify `CheckoutAction` is still working as expected with new "status" labels.
2. Verify `CheckoutActions` is still working as expected with new "status" labels.
3. Verify documentation changes are correct

feat: 265 nnnnat checkout action status labels

---

package/src/components/Button/v1/Button.js

Resolves #295 
Impact: minor
Type: bugfix
Disable cursor pointer when a button is disabled
1. In the button component, scroll to a disabled button example
2. Verify the cursor pointer is not visible when the mouse hovers over the a disabled button.

fix: disable cursor pointer if a button is disabled

---

package/src/components/AccountProfileInfo/v1/AccountProfileInfo.js
package/src/components/AccountProfileInfo/v1/AccountProfileInfo.md
package/src/components/AccountProfileInfo/v1/AccountProfileInfo.test.js
package/src/components/AccountProfileInfo/v1/__snapshots__/AccountProfileInfo.test.js.snap
package/src/components/AccountProfileInfo/v1/index.js
package/src/components/Button/v1/Button.js
package/src/components/Button/v1/Button.md
package/src/components/Button/v1/__snapshots__/Button.test.js.snap
package/src/components/CartEmptyMessage/v1/__snapshots__/CartEmptyMessage.test.js.snap
package/src/components/ProfileImage/v1/ProfileImage.js
package/src/components/ProfileImage/v1/ProfileImage.md
package/src/components/ProfileImage/v1/ProfileImage.test.js
package/src/components/ProfileImage/v1/__snapshots__/ProfileImage.test.js.snap
package/src/components/ProfileImage/v1/index.js
package/src/tests/mockComponents.js
package/src/theme/defaultComponentTheme.js
styleguide.config.js
styleguide/src/appComponents.js
styleguide/src/sections/Account.md

Resolves #250 
- Create an AccountProfileInfo component which shows user icon, name, email address, and link to edit account info
- Image is taken from Gravatar
- Similar to ViewerInfo component that displays info in the Nav
ProfileImage component with Image:
ProfileImage component with initials:
AccountProfileInfo component:
With edit link:
None
- Verify an image shows in the ProfileImage component when `profileImage` is provided
- Verify initials are shown when no `profileImage` is provided
- Verify you can change the size of the image (or initials) with the `size` prop
- Verify that the initials change size with the `size` prop
- Verify the data shows correctly
- Verify edit link shows when `shouldShowEditButton` prop is `true`
- Verify …

(feat): AccountProfileInfo component

---

package/README.md
package/src/components/StripeForm/v1/StripeForm.js
styleguide/src/sections/InstallingandImporting.md

Resolves #325 
- Remove `withTheme` to hopefully resolve the error in the linked issue. This error does not happen locally, even in the production build, so this is only an educated guess at what is causing it.
- Correct some omissions in the installation docs, unrelated
None
Hopefully there will not be errors when this PR preview is deployed. Otherwise just review the code changes.

Fix StripeForm error

---

package/src/components/CheckoutActions/v1/CheckoutActions.md

Resolves #327 
Type: **bugfix|docs**
`FulfillmentOptionsCheckoutAction` wasn't working correctly in the `CheckoutActions` example and throwing an error.
The issue was being caused by a mistake in the mocked GQL data. (`id` => `_id`).
N/A
1. Visit `CheckoutActions` doc page and complete the checkout steps.

docs: fixed CheckoutActions example

---

package/src/components/AddressForm/v1/AddressForm.js

Inside of <AddressForm>, updating a label to be “Name” instead of “Full Name”
None 
See that field displays Name as the label instead of Full Name

fix: change label from Full Name to Name

---

package/src/components/AccountProfileInfo/v1/AccountProfileInfo.js
package/src/components/AccountProfileInfo/v1/AccountProfileInfo.md
package/src/components/AccountProfileInfo/v1/AccountProfileInfo.test.js

After working with the AccountProfileInfo component with live data, we've seen that `name`, `firstName` and `lastName` fields are not always present on an account. For instance a brand new account has none of the fields attached to it.
This PR removes the `isRequired` from these fields so that the component will display without error even when a name is not present.
It also adds a check to display the fields in the following order: `name`, `firstName + lastName`, `firstName`, `null`.
None
- Try different combinations of having `name`, `firstName`, and `lastName` fields on a `viewer` object and make sure the component renders at all times, either with a full name (name OR firstName + lastName), first name only, or no name at all.

refactor: remove `isRequired` from name, firstName, lastName fields of ProfileInfo

---

package/src/components/AddressBook/v1/AddressBook.js
package/src/components/AddressForm/v1/AddressForm.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.md
package/src/utils/CustomPropTypes.js

Resolves #331 
Added `address` and `addressBook` ProptTpes to CustomPropTypes
N/A
1. View [AddressForm](https://deploy-preview-333--stoic-hodgkin-c0179e.netlify.com/#!/AddressForm) PropTypes table.
2. View [AddressBook](https://deploy-preview-333--stoic-hodgkin-c0179e.netlify.com/#!/AddressBook) PropTypes table.
3. View [ShippingAddressCheckoutAction](https://deploy-preview-333--stoic-hodgkin-c0179e.netlify.com/#!/ShippingAddressCheckoutAction) PropTypes table.
4. See components all use a "Custom" PropType description.

feat: address CustomPropTypes

---

styleguide.config.js
styleguide/src/sections/ComponentsContext.md

Type: **docs**
Adds a style guide section: "Understanding Component References"

Add "Understanding Component References" section

---

package/src/components/Address/v1/Address.js
package/src/components/Address/v1/Address.md
package/src/components/Address/v1/Address.test.js
package/src/components/Address/v1/__snapshots__/Address.test.js.snap
package/src/components/Address/v1/index.js
package/src/components/AddressBook/v1/AddressBook.js
package/src/components/AddressBook/v1/AddressBook.md
package/src/components/AddressReview/v1/AddressReview.js
package/src/components/AddressReview/v1/AddressReview.md
package/src/components/AddressReview/v1/AddressReview.test.js
package/src/components/AddressReview/v1/__snapshots__/AddressReview.test.js.snap
package/src/components/SelectableItem/v1/SelectableItem.js
package/src/components/SelectableItem/v1/SelectableItem.md
package/src/components/SelectableItem/v1/__snapshots__/SelectableItem.test.js.snap
package/src/components/SelectableList/v1/SelectableList.js
package/src/components/SelectableList/v1/SelectableList.md
package/src/theme/colors.js
package/src/theme/defaultComponentTheme.js
package/src/utils/addressToString.js
package/src/utils/index.js
styleguide.config.js
styleguide/src/appComponents.js

Resolves #122 & #277 
**AddressReview**
*  Based on this [spec](https://github.com/reactioncommerce/reaction-component-library/issues/122)
**Address**
*  Created an Address component that displays an Address
**SelectableList Enhancement** 
*   Adds `isHorizontal` prop: Updated to allow a horizontal layout along with the vertical style.
*   Adds `isStacked` prop: Updated to allow `detail` to display stacked under the label along with the right/left aligned.
⚠️ The alert is not part of this component. The alert will be worked on next. This alert is just a mock-up.
N/A
1. **AddressReview**: https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/AddressReview
* Open broswer console and test the example implamentation towards the bottom of the …

feat: AddressReview component

---

package/src/components/AddressBook/v1/AddressBook.js
package/src/components/AddressReview/v1/AddressReview.js
package/src/components/AddressReview/v1/AddressReview.md
package/src/components/AddressReview/v1/__snapshots__/AddressReview.test.js.snap
package/src/components/CheckoutActions/v1/CheckoutActions.js
package/src/components/CheckoutActions/v1/CheckoutActions.md
package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.js
package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.md
package/src/components/FulfillmentOptionsCheckoutAction/v1/__snapshots__/FulfillmentOptionsCheckoutAction.test.js.snap
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.md
package/src/components/ShippingAddressCheckoutAction/v1/__snapshots__/ShippingAddressCheckoutAction.test.js.snap
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.md
package/src/components/StripePaymentCheckoutAction/v1/__snapshots__/StripePaymentCheckoutAction.test.js.snap

Resolves #338 
* Updated `ShippingAddressCheckoutAction` to accept a `validation` method and `alert` object as a component props, to display the `AddressReview` and an `InlineAlert` if an address validation issue.
*  If the `validation` method is available the form will validate the entered address, 
*  If the entered address is invalid the component will switch from the `AddressForm` to the `AddressReview` and display the entered and "suggested" addresses.
* if there is an address validation error, the error message can be used as the alert message.
* Removed the warning from `AddressReview` in favor of the `InlineAlert` pattern.
* Updated `CheckoutActions` example to have fake address validation issues
N/A
1. Test the two …

feat: 338 nnnnat shipping address review

---

package/src/components/Select/v1/Select.js
package/src/components/Select/v1/Select.test.js

When using `Select` component, I noticed that when `value` prop was initially set and then became `null`, it was not clearing the selection.
There is a test proving it works, but if you want to test in the UI, you can add the following to the markdown file temporarily.
```
```jsx
const options = [
{ value: 'chocolate', label: 'Chocolate' },
{ value: 'darkchocolate', label: 'Dark Chocolate' },
{ value: 'mintchip', label: 'Mint Chip' },
{ value: 'strawberry', label: 'Strawberry' },
{ value: 'vanilla', label: 'Vanilla' },
];
initialState = { value: "vanilla" };
const handleChange = () => {
setState({ value: null })
};
<div>
<p>{state.value}</p>
<Select options={options} value={state.value} />
<Button onClick={handleChange}>Change</Button>
</div>
;```
```

fix: clear Select when value prop becomes null

---

package/src/components/CartItem/v1/CartItem.js
package/src/components/CartItem/v1/CartItem.md
package/src/components/CartItem/v1/CartItem.test.js
package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap
package/src/components/CartItemDetail/v1/CartItemDetail.md
package/src/components/CartItemDetail/v1/CartItemDetail.test.js
package/src/components/CartItemDetail/v1/__snapshots__/CartItemDetail.test.js.snap
package/src/components/CartItems/v1/CartItems.js
package/src/components/CartItems/v1/CartItems.md
package/src/components/CartItems/v1/CartItems.test.js
package/src/components/CheckoutActions/v1/CheckoutActions.md
package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.md
package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.test.js
package/src/components/MiniCart/v1/MiniCart.md
package/src/components/MiniCart/v1/MiniCart.test.js

Resolves #357
- Adds `productURLPath` to the way image URLs are created, so that products linked from images can also have more complex url paths
- Changes `productSlug` to proper slug format: `slug-format` in all tests and docs
0. CartItemDetails: Link still works w/o a slash before the slug - https://deploy-preview-349--stoic-hodgkin-c0179e.netlify.com/#!/CartItemDetail 
1. CartItem image URL works -https://deploy-preview-349--stoic-hodgkin-c0179e.netlify.com/#!/CartItem
2. FinalReviewCheckoutAction image: https://deploy-preview-349--stoic-hodgkin-c0179e.netlify.com/#!/FinalReviewCheckoutAction
3. MiniCart image: https://deploy-preview-349--stoic-hodgkin-c0179e.netlify.com/#!/MiniCart

fix(cartitem): add productURLPath to image link

---

package/src/components/Accordion/v1/Accordion.md
package/src/components/AccordionFormList/v1/AccordionFormList.js
package/src/components/AccordionFormList/v1/AccordionFormList.md
package/src/components/AccordionFormList/v1/AccordionFormList.test.js
package/src/components/AccordionFormList/v1/__snapshots__/AccordionFormList.test.js.snap
package/src/components/AccordionFormList/v1/index.js
package/src/components/AddressBook/v1/AddressBook.js
package/src/components/AddressBook/v1/AddressBook.md
package/src/components/AddressBook/v1/__snapshots__/AddressBook.test.js.snap
package/src/tests/mockComponents.js
package/src/theme/defaultComponentTheme.js
styleguide.config.js
styleguide/src/appComponents.js
styleguide/src/sections/InstallingandImporting.md

Creates an `AccordionFormList` component that is based on `AddressBook`, but without being specific to addresses. Then updates `AddressBook` to use it.
Also added the missing `Theme` section to the docs for some affected components, though I didn't try to document every missing theme variable. All theme variables for the new `AccordionFormList` (formerly for `AddressBook`) are documented now.
In the theme, need to change `AddressBook` group to `AccordionFormList`. The variable names within it are the same.
1. Test the new component
2. Test `AddressBook` to ensure it still looks and works the same as previously.

New AccordionFormList component

---

package/src/components/AddressForm/v1/AddressForm.js
package/src/components/RegionInput/v1/RegionInput.js
package/src/components/RegionInput/v1/RegionInput.md
package/src/components/RegionInput/v1/RegionInput.test.js
package/src/components/RegionInput/v1/__snapshots__/RegionInput.test.js.snap
package/src/components/RegionInput/v1/index.js
package/src/tests/mockComponents.js
styleguide.config.js
styleguide/src/appComponents.js
styleguide/src/sections/InstallingandImporting.md

Resolves #345 
- Creates `RegionInput` component, pulling https://github.com/reactioncommerce/reaction-component-library/blob/97a0d91f5d03dd7262e69633960b17cd8194d997/package/src/components/AddressForm/v1/AddressForm.js#L392 out of `AddressForm` and into its own re-usable component
- Adds docs and tests for various scenarios: TextInput field, Select field, a pre-filled TextInput field, a pre-filled Select field
- Refactors `AddressForm` to use `RegionInput`
- I corrected a spelling on a prop object value: https://github.com/reactioncommerce/reaction-component-library/pull/354/files#diff-f9fd26feeb715b8d3d2968faa3f81589L110
1. RegionInput: https://deploy-preview-354--stoic-hodgkin-c0179e.netlify.com/#!/RegionInput
2. AddressForm: …

feat(regioninput): add RegionInput component, use in AddressForm

---

package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.js
package/src/components/InlineAlert/v1/InlineAlert.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js
package/src/utils/CustomPropTypes.js

Resolves N/A
Type: **feature|bugfix|refactor**
* Created an `alert` custom proptype and updated all consuming components to use it.
* Fix proptype issue in InlineAlert
N/A
1. View the StripePaymentCheckoutAction, FulfillmentOptionsCheckoutAction and ShippingAddressCheckoutAction docs and verify it's using the custom `alert` proptype.

feat: nnnnat alert custom proptype

---

package/src/components/RegionInput/v1/RegionInput.js

Hotfixing `RegionInput` with `isFormInput` and wrapping the component so that the input is compliant with Reacto-Form in its current state, and does not break the AddressForm.

fix(regioninput): add isFormInput back to RegionInput

---

package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js

Resolves #357
Impact: **critical**  
- If a user clicks **Use a different billing address**, and then clicks **Same as shipping address** with a blank address form, check to see if the `StripeForm` is complete to enable the **Save** button to be clicked, by running `this.handleStripeFormIsComplete();`
- Creates and sets `isStripeFormComplete` state
Test https://deploy-preview-359--stoic-hodgkin-c0179e.netlify.com/#!/CheckoutActions
1. Do step 1 and 2
2. Fill out credit card
3. Click `Use a different address`
4. _then_ Click `Use same`

fix(stripepaymentcheckoutaction): check for Stripe Form completion

---

package/src/components/AddressBook/v1/AddressBook.md
package/src/components/InlineAlert/v1/InlineAlert.js
package/src/components/InlineAlert/v1/InlineAlert.md
package/src/components/InlineAlert/v1/InlineAlert.test.js
package/src/components/InlineAlert/v1/__snapshots__/InlineAlert.test.js.snap
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.md

Resolves #363 
- Change `defaultProps` from `alertType: information` and `message: Alert` to empty strings
- An empty `alertType` will change the CSS to `display: none`
- Test: Add empty alert test
1. Add `alert={{}}` to any of the 3 CheckoutActions with Alerts (Shipping, Fulfillment, Address): https://deploy-preview-364--stoic-hodgkin-c0179e.netlify.com/#!/StripePaymentCheckoutAction
2. InlineAlert docs: https://deploy-preview-364--stoic-hodgkin-c0179e.netlify.com/#!/InlineAlert

fix(inlinealerts): #363 empty alerts should not be displayed

---

package/src/components/AddressReview/v1/AddressReview.js
package/src/components/AddressReview/v1/AddressReview.md

Resolves N/A
Impact: **critical**  
`AddressReview` component was built expecting that validation result address object would match the Reaction GQL `Address` type. This is not the case for several address properties (i.e., `fullName` & `phone`) on validation results. I've added a simple transform method that will copy those missing properties over to any suggested address that gets selected.
N/A
1. Visit the [AddressReview docs](https://deploy-preview-365--stoic-hodgkin-c0179e.netlify.com/#!/AddressReview) and test the implementation example.
2. Select the "Suggested Address" and click submit.
3. Verify that the `fullName`, `phone` & `isCommercial` properties have been copied over to the selected address.

fix(addressreview): xform validated address when selected

---

package/src/components/AddressCapture/v1/AddressCapture.js
package/src/components/AddressCapture/v1/AddressCapture.md
package/src/components/AddressCapture/v1/AddressCapture.test.js
package/src/components/AddressCapture/v1/__snapshots__/AddressCapture.test.js.snap
package/src/components/AddressCapture/v1/index.js
package/src/components/AddressForm/v1/AddressForm.js
package/src/components/AddressForm/v1/AddressForm.md
package/src/components/CheckoutActions/v1/CheckoutActions.md
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.md
package/src/components/ShippingAddressCheckoutAction/v1/__snapshots__/ShippingAddressCheckoutAction.test.js.snap
package/src/tests/mockComponents.js
styleguide.config.js
styleguide/src/appComponents.js

Resolves N/A
Type: **bugfix|refactor**
Currently, the `AddressForm` & `AddressReview` are sibling components leaving the responsibility of switching UI to a parent when an `address` has been validated. This causes a situation where we have to implement at least 3 parent components to control this flow.
~~To make the validation UI more portable move the UI switching logic of the address validation flow to the `AddressForm` component.~~
Created a wrapper component that orchestrates an address validation UX flow using the `AddressForm` and `AddressReview` components.
N/A
1. Visit [AddressCapture docs](https://deploy-preview-366--stoic-hodgkin-c0179e.netlify.com/#!/AddressCapture) and test the example implementations.
2. Test the simple example with the console open to see …

fix: nnnnat drop-in address validation

---

package/src/components/CartSummary/v1/CartSummary.js
package/src/components/CartSummary/v1/CartSummary.md
package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.js
package/src/theme/defaultComponentTheme.js

CartSummary existing component
None
1. See that surcharges are visible, when applicable, in CartSummary component

feat: add surcharge to Cart Summary

---

package/src/components/CartItem/v1/CartItem.js
package/src/components/CartItem/v1/CartItem.md
package/src/components/CartItem/v1/CartItem.test.js
package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap
package/src/components/CartItems/v1/CartItems.md
package/src/theme/defaultComponentTheme.js

Resolves #369 
- When an item has a quantity of more than one, display the subtotal cost of all of the items.
- This applies to Cart and MiniCart.
1. Test CartItems in regular mode and MiniCart mode
2. Test CartItems in desktop and mobile mode

feat(#369): CartItem - Display Subtotal

---

package/src/components/Address/v1/Address.js
package/src/components/Address/v1/__snapshots__/Address.test.js.snap
package/src/components/AddressCapture/v1/AddressCapture.js
package/src/components/CheckoutActions/v1/CheckoutActions.md
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.md

Resolves #374 #373 
AddressCapture component would allow the submission of invalid addresses in some cases.
Address component postal code would cause a weird line break with long addresses.
@cassytaylor part of the issue was we could have an invalid address with 0 suggested address. If that is the case I'm applying error state to the AddressForm and showing the validation error message above in an InlineAlert.
N/A
1. Visit the [CheckoutActions docs]() and enter a shipping address with a postal code of "10111".
2. The action shoudl encounter a validation error without and suggestions. The form should show field errror state and an InlineAlert should appear.
3. Visit the [Address docs]() and verify the postal code is on a new line.

fix: 374 nnnnat address validaiton bugs

---

package.json
package/src/components/AddressCapture/v1/AddressCapture.js
package/src/components/AddressReview/v1/AddressReview.test.js
package/src/components/ErrorsBlock/v1/ErrorsBlock.js
package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.js
package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.js
package/src/components/InlineAlert/v1/InlineAlert.js
package/src/components/PhoneNumberInput/v1/PhoneNumberInput.js
package/src/components/RegionInput/v1/RegionInput.js
package/src/components/SelectableList/v1/SelectableList.js
package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js
package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js
package/src/components/TextInput/v1/TextInput.js
package/src/svg/iconPlus.js
yarn.lock

Previously `withComponents` HOC did not hoist non-React `static` props, so we had code at the bottom of many component files hoisting or setting statics. This pulls in the latest `components-context` package release, which has a fixed `withComponents`. I've removed the workaround code.
None
Make sure that affected components, mainly forms and CheckoutAction steps still seem to work properly.

Update components context

---

package/src/components/InventoryStatus/v1/InventoryStatus.js
package/src/components/InventoryStatus/v1/InventoryStatus.md
package/src/components/InventoryStatus/v1/InventoryStatus.test.js
package/src/components/InventoryStatus/v1/__snapshots__/InventoryStatus.test.js.snap
package/src/components/InventoryStatus/v1/index.js
package/src/components/InventoryStatus/v1/utils/index.js
package/src/components/InventoryStatus/v1/utils/inventoryStatus.js
package/src/components/InventoryStatus/v1/utils/inventoryStatus.test.js
package/src/components/InventoryStatus/v1/utils/isProductBestseller.js
package/src/components/InventoryStatus/v1/utils/isProductBestseller.test.js
package/src/components/InventoryStatus/v1/utils/isProductLowQuantity.js
package/src/components/InventoryStatus/v1/utils/isProductLowQuantity.test.js
package/src/components/InventoryStatus/v1/utils/statusLabels.js
package/src/components/InventoryStatus/v1/utils/statusLabels.test.js
package/src/components/InventoryStatus/v1/utils/statusTypes.js
package/src/components/InventoryStatus/v1/utils/statusTypes.test.js
styleguide.config.js
styleguide/src/appComponents.js

This new component uses similar logic as that of `BadgeOverlay` to determine the inventory status of a product / variant / option, an return text related to that status.
This component uses the existing `StockWarning` component if the inventory status is `isLowQuantity`, otherwise it returns new text.
None.
1. See that the message changes based on different `isBackorder`, `isLowQuantity`, and `isSoldOut` data.

feat: add new inventoryStatus component

---

package/src/components/CartSummary/v1/CartSummary.js
package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap
package/src/components/TextInput/v1/TextInput.js

Resolves #385
`.extend` is deprecated and logging warnings
Only `CartSummary` and `TextInput` are affected. Verify that they still work and look as expected.

chore: switch styled-components `.extend` to `styled()`

---

docs/README.md
docs/contributing.md

Signed-off-by: Mathias Meyer <meyer@paperplanes.de>
We're adopting the Developer Certificate of Origin process to document contributions and acknowledgement of the Apache 2.0 license (introduced in #377).
The goals of this change are:
- Ensuring explicit sign-off on community contributions, especially from corporate clients and their employees, to ensure contributions were made with the understanding of a) the license and b) the contributor's authority to provide the patch to Reaction as an open source project.
- Keeping legal overhead to a minimum, e.g. by avoiding complex legal language and a signing process. We want to encourage people to contribute, not put them off with legalese they may need to discuss with their lawyer before contributing.
- We want to keep the steps involved as …

chore: Adopt Developer Certificate of Origin in documentation.

---

package.json
package/package.json
styleguide/src/sections/InstallingandImporting.md
yarn.lock

The `components-context` dependencies are out of date. This caused an issue in reaction core with the latest component library installed with v1.0.0 of components-context broke `reacto` form validation and submitting.
none.
ensure the form fields are working and submitting properly. The best example of this is the final example on the AddressBook component page.

fix/chore: component context dependencies

---

.snyk
styleguide/src/sections/InstallingandImporting.md

Resolves #399 
Type: **docs**
Updated the Installing and Importing article to explain how to avoid EcmaScript module errors with Webpack (NextJS / create-react-app).

docs: add mjs config details to installation docs

---

package/src/components/AddressChoice/v1/AddressChoice.js

Resolves #405
Type: **bugfix|**
`AddressChoice`
None
1. In `CheckoutActions`, enter shipping address and select shipping method.
2. When payment form is rendered, check the `state` of `PaymentsCheckoutAction`, the billing address should be the same as the shipping address.
3. Change a field in Shipping address and save it. Check that the `state` of `PaymentsCheckoutAction` has been updated.

fix: trigger onChange when new address is received

---

styleguide.config.js
styleguide/src/sections/LocalDevelopment.md

Type: **docs**
Adding instructions on how to use a local version of the component library inside storefront and the operator UI. Instructions taken, and slightly modified per repo, from here: https://github.com/reactioncommerce/reaction-component-library/pull/395

docs: how to test component library locally

---

package/src/components/ShopLogo/v1/ShopLogo.js
package/src/components/ShopLogo/v1/ShopLogo.md
package/src/components/ShopLogo/v1/__snapshots__/ShopLogo.test.js.snap
package/src/theme/defaultComponentTheme.js

Resolves #403
There was no way to set `ShopLogo`'s `img` height through theming, which is a bit of a pain when using vector images as they appear huge by default.
Here's a test with `
None.
1. Change the value of `ShopLogo.height` in `src/theme/defaultComponentTheme.js`.
2. See that the the placeholder image is now at your desired height on `http://localhost:4040/#!/ShopLogo`.

Add height theme prop to ShopLogo

---

package/src/components/SelectableItem/v1/SelectableItem.js
package/src/components/SelectableItem/v1/__snapshots__/SelectableItem.test.js.snap
package/src/components/SelectableList/v1/SelectableList.js

Signed-off-by: Machiko Yasuda <machiko@reactioncommerce.com>
Type: **bugfix|refactor**
- Moved CSS styles from `SelectableList` down to the child, `SelectableItem` so that the styles only apply to the `detail` element, and not any other `div` that is in `SelectableList`.
- Should look the same
1. Test that `isHorizontal` lists look and work the same way: https://deploy-preview-407--stoic-hodgkin-c0179e.netlify.com/#!/AddressReview
2. Test this branch on projects that use the Component Library
1. Change `package.json` to: ` "@reactioncommerce/components": "reactioncommerce/reaction-component-library#236-machikoyasuda-fix-horizwrap",`
2. `docker-compose up --build`
3. Open the app and find somewhere where a horizontal SelectableList is used - often in AddressReview

fix(selectableitem): remove cascading div styling

---

.snyk
babel.config.js

Changed Babel config.
Previously, when building the `mjs` ES module files, they were being transformed to target only modern browsers that support ES modules. We intended to keep IE11 support in those files, so this was wrong. For example, the built `mjs` files still contained arrow functions, which IE11 doesn't understand.
Now, the `mjs` files are still ES module files that Webpack can tree shake, but all code within them except for the `import` and `export` lines are transpiled the same way as for `js` files. For example, arrow functions become regular functions and thus are understood by IE11.
Run `yarn build` command in the `/package` directory and look at the `.mjs` files created in `dist`. They should have all of the Babel transformations such as …

fix: babel transform mjs files

---

styleguide.config.js

Signed-off-by: Christopher Shepherd <christopher@reactioncommerce.com>
Closes: https://github.com/reactioncommerce/reaction-component-library/issues/422
No components or dependencies changed, just updated styleguidist.config.js so that every topic gets its own page instead of rendering the whole style guide on one huge slow page

fix styleguidist configuration so that everything gets its own page

---

package/src/components/Checkbox/v1/Checkbox.js
package/src/components/TextInput/v1/TextInput.js
package/src/components/TextInput/v1/TextInput.md

Updated `TextInput` component to add `type === number` to the valid `types`, and also added `number` specific props `min`, `max`, and `step`.
None, this will only add features
1. Use `type="number` on a `TextField`, and add `min`, `max`, and `step`
1. See that these fields work as they should, not going higher than the max when using the arrows, and set the `step=".01"` and see that the number increments by `.01` instead of full numbers.

feat: add number type and number related  props to TextInput

---

.snyk
babel.config.js

Resolves #432 
The published package files have imports of "core-js" package paths, which are different between v2 and v3 of core-js. This creates an unnecessary requirement that the app using this package must use either v2 or v3, depending on what was used to publish this package.
Changes the Babel config so that these imports are not added to the built files. This means that there is now an expectation that the app using this package will have polyfilled all runtime APIs that this package needs. We may want to document the exact ones, but for now we should tell apps to load everything by doing this before all other code:
```js
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```
Or if using Babel, use `useBuiltIns: 'entry'` in Babel …

fix: remove core-js deps from published build

---

styleguide/src/sections/LocalDevelopment.md

Style guide section docs update. The local link instructions were incorrect and didn't work.

docs: fix Reaction Admin pkg link example

---

package/src/components/AccordionFormList/v1/AccordionFormList.js

Part of: #409 
AccordionFormList now has overrides when i18next will be implemented (see #409)
1. Add a new prop `cancelButtonText` or `saveButtonText` to `<AccordionFormList />` 
2. Add the value `"test"` to either cancelButtonText or saveButtonText
3. Button should display "test" when test is given as a value to the prop. When the prop `cancelButtonText` or `saveButtonText` is not added, it should default to the values given in default props

feat: added label overrides on AccordionFormList

---

package/src/components/AccountProfileInfo/v1/AccountProfileInfo.js

Part of: #409 
AccountProfileInfo now has overrides when i18next will be implemented (see #409)
1. Add a new prop `editAccountButtonText` or to `<AccountProfileInfo />` 
2. Add the value `"test"` to editAccountButtonText
3. Button should display "test" when test is given as a value to the prop. When the prop `editAccountButtonText` is not added, it should default to the values given in default props

feat: added  label overrides on AccountProfileInfo

---

package/src/components/AddressBook/v1/AddressBook.js

Part of: #409 
AddressBook now has label overrides for when i18next will be implemented (see #409)
1. Add a new prop `addNewItemButtonText`,`deleteItemButtonText` or `entryFormSubmitButtonText` to `<AddressBook />` 
2. Add the value `"test"` to `addNewItemButtonText`,`deleteItemButtonText` or `entryFormSubmitButtonText`
3. Button should display "test" when test is given as a value to the prop. When the prop `addNewItemButtonText`,`deleteItemButtonText` or `entryFormSubmitButtonText` is not added, it should default to the values given in default props

feat: added  label overrides on AddressBook

---

package/src/components/AddressCapture/v1/AddressCapture.js

Part of: #409 
AddressCapture now has label overrides for when i18next will be implemented (see #409)
1. Add a new prop `editButtonText` to `<AddressCapture />` 
2. Add the value `"test"` to `editButtonText`
3. Button should display "test" when test is given as a value to the prop. When the prop `editButtonText` is not added, it should default to the values given in default props.

feat: added  label overrides on AddressCapture

---

package/src/components/AddressForm/v1/AddressForm.js

Part of: #409 
AddressCapture now has label overrides for when i18next will be implemented (see #409)
addressNamePlaceholder should be renamed to addressNamePlaceholderText for consistency. It is important to state what the placeholder is, in this case we only support strings. Not adding text might confuse people that they can add images as placeholders. 
The following props are added to this component
```
address1LabelText: PropTypes.string,
address1PlaceholderText: PropTypes.string,
address2LabelText: PropTypes.string,
address2PlaceholderText: PropTypes.string,
addressNameLabelText: PropTypes.string,
cityLabelText: PropTypes.string,
cityPlaceholderText: PropTypes.string,
countryLabelText: PropTypes.string,
countryPlaceholderText: PropTypes.string, …
```

feat: added label and placeholder overrides on AddressForm

---

package/src/components/AddressReview/v1/AddressReview.js

Part of: #409 
AddressCapture now has label overrides for when i18next will be implemented (see #409)
addressNamePlaceholder should be renamed to addressNamePlaceholderText for consistency. It is important to state what the placeholder is, in this case we only support strings. Not adding text might confuse people that they can add images as placeholders. 
The following props are added to this component
```
addressEnteredLabelText: PropTypes.string,
addressSuggestionLabelText: PropTypes.string,
```
```
addressEnteredLabelText: "Entered Address"
addressSuggestionLabelText: "Suggested Address"
```
1. Add a new prop from added props list to `<AddressReview />` 
2. Add the value `"test"` to any new prop …

feat: added label overrides on AddressReview

---

package/src/components/CheckoutActionComplete/v1/CheckoutActionComplete.js

Part of: #409 
CheckoutActionComplete now has overrides when i18next will be implemented (see #409)
1. Add a new prop `changeButtonText` to `<CheckoutActionComplete />` 
2. Add the value `"test"` to `changeButtonText`
3. Button should display "test" when test is given as a value to the prop. When the prop `changeButtonText` is not added, it should default to the values given in default props

feat: added text override on CheckoutActionComplete

---

package/src/components/CheckoutEmailAddress/v1/CheckoutEmailAddress.js

Part of: #409 
CheckoutEmailAddress now has overrides when i18next will be implemented (see #409)
1. Add a new prop `signedInText` to `<CheckoutEmailAddress />` 
2. Add the value `"test"` to `signedInText`
3. Button should display "test" when test is given as a value to the prop. When the prop `signedInText` is not added, it should default to the values given in default props
```
signedInText: PropTypes.string,
```

feat: added text overrides on CheckoutEmailAddress

---

package/src/components/Field/v1/Field.js

Part of: #409 
Field now has overrides when i18next will be implemented (see #409)
1. Add a new prop `optionalLabelText` to `<Field />` 
2. Add the value `"test"` to `optionalLabelText`
3. Button should display "test" when test is given as a value to the prop. When the prop `optionalLabelText` is not added, it should default to the values given in default props
```
optionalLabelText: PropTypes.string,
```

feat: added text overrides on Field

---

package/src/components/FulfillmentOptionsCheckoutAction/v1/FulfillmentOptionsCheckoutAction.js

Part of: #409 
FulfillmentOptionsCheckoutAction now has overrides when i18next will be implemented (see #409)
1. Add a new prop `emptyMessageLabelText` to `<FulfillmentOptionsCheckoutAction />` 
2. Add the value `"test"` to `emptyMessageLabelText`
3. Button should display "test" when test is given as a value to the prop. When the prop `emptyMessageLabelText` is not added, it should default to the values given in default props
```
emptyMessageLabelText: PropTypes.string,
```

feat: added text overrides on FulfillmentOptionsCheckoutAction

---

package/src/components/GuestForm/v1/GuestForm.js

Part of: #409 
GuestForm now has overrides when i18next will be implemented (see #409)
1. Add a new prop `emailLabelText` to `<GuestForm />` 
2. Add the value `"test"` to `emailLabelText`
3. Button should display "test" when test is given as a value to the prop. When the prop `emailLabelText` is not added, it should default to the values given in default props
```
emailLabelText: PropTypes.string,
emailPlaceholderText: PropTypes.string
```

feat: added text overrides on GuestForm

---

package/src/components/MiniCart/v1/MiniCart.js

Part of: #409 
MiniCart now has overrides when i18next will be implemented (see #409)
1. Add a new prop `checkoutButtonText` to `<MiniCart />` 
2. Add the value `"test"` to `checkoutButtonText`
3. Button should display "test" when test is given as a value to the prop. When the prop `checkoutButtonText` is not added, it should default to the values given in default props
```
checkoutButtonText: PropTypes.string,
footerMessageText: PropTypes.string
```

feat: added text overrides on MiniCart

---

package/src/components/MiniCartSummary/v1/MiniCartSummary.js

Part of: #409 
MiniCartSummary now has overrides when i18next will be implemented (see #409)
1. Add a new prop `subtotalLabelText` to `<MiniCartSummary />` 
2. Add the value `"test"` to `subtotalLabelText`
3. Button should display "test" when test is given as a value to the prop. When the prop `subtotalLabelText` is not added, it should default to the values given in default props
```
taxLabelText: PropTypes.string,
subtotalLabelText: PropTypes.string
```

feat: added text overrides on MiniCartSummary

---

package/src/components/PaymentsCheckoutAction/v1/PaymentsCheckoutAction.js

Part of: #409 
PaymentsCheckoutAction now has overrides when i18next will be implemented (see #409)
1. Add a new prop `billingAddressTitleText` to `<PaymentsCheckoutAction />` 
2. Add the value `"test"` to `billingAddressTitleText`
3. Button should display "test" when test is given as a value to the prop. When the prop `billingAddressTitleText` is not added, it should default to the values given in default props
```
billingAddressTitleText: PropTypes.string,
```

feat: added text overrides on PaymentsCheckoutAction

---

package/src/components/StripePaymentInput/v1/StripePaymentInput.js

Part of: #409 
StripePaymentInput now has overrides when i18next will be implemented (see #409)
1. Add a new prop `secureCaptionText` to `<StripePaymentInput />` 
2. Add the value `"test"` to `secureCaptionText`
3. Button should display "test" when test is given as a value to the prop. When the prop `secureCaptionText` is not added, it should default to the values given in default props
```
secureCaptionText: PropTypes.string,
```

feat: added text overrides on StripePaymentInput

---

package/src/components/CartItem/v1/CartItem.js

Part of: #409
Impact: minor
Type: feature
Component
CartItem now has overrides when i18next will be implemented (see #409)
Breaking changes
Testing
Add a new prop `messageText` or `totalText` to `<CartItem />`
Add the value "test" to either `messageText` or `totalText`
Button or title should display "test" when test is given as a value to the prop. When the prop `messageText` or `totalText` is not added, it should default to the values given in default props

feat: added text overrides on CartItem

---

package/src/components/CheckoutActions/v1/CheckoutActions.js

Part of: #409 
CheckoutActions now has overrides when i18next will be implemented (see #409)
1. Add a new prop `cancelButtonText` to `<CheckoutActions />` 
2. Add the value `"test"` to `cancelButtonText`
3. Button should display "test" when test is given as a value to the prop. When the prop `cancelButtonText` is not added, it should default to the values given in default props
```
cancelButtonText: PropTypes.string,
isNotSavingButtonText: PropTypes.string,
isSavingButtonText: PropTypes.string,
saveButtonText: PropTypes.string,
```

feat: added text overrides on CheckoutActions

---

package/src/components/StripePaymentCheckoutAction/v1/StripePaymentCheckoutAction.js

Part of: #409 
StripePaymentCheckoutAction now has overrides when i18next will be implemented (see #409)
1. Add a new prop `billingAddressTitleText` to `<StripePaymentCheckoutAction />` 
2. Add the value `"test"` to `billingAddressTitleText`
3. Button should display "test" when test is given as a value to the prop. When the prop `billingAddressTitleText` is not added, it should default to the values given in default props
```
billingAddressTitleText: PropTypes.string,
secureCaptionText: PropTypes.string,
```

feat: added text overrides on StripePaymentCheckoutAction
