reactioncommerce/reaction-component-library

src/components/ErrorsBlock/v1/ErrorsBlock.js, src/components/ErrorsBlock/v1/ErrorsBlock.md, src/components/ErrorsBlock/v1/ErrorsBlock.test.js, src/components/ErrorsBlock/v1/__snapshots__/ErrorsBlock.test.js.snap, src/components/Field/v1/Field.md, src/defaultComponentTheme.js, styleguide.config.js
Resolves #73 
Create ErrrorsBlock component
We've decided to use [reacto-form](http://forms.dairystatedesigns.com/reacto-form/) to manage our form's state. Reacto form breaks apart what we were calling the `TextField` into 3 separate components, a `Field` component that wraps an input/errors and provides the label rendering, an `Input` component that renders the actual input field and an `ErrorsBlock` component that will display a field's error message.
The ErrorsBlock works as a typical user would expect, and matches the designs in #18 
This component still needs complete documentation
=> (feat): 73 nnnnat errors block component

package.json, src/components/Select/v1/Select.js, src/components/Select/v1/Select.md, src/components/Select/v1/Select.test.js, src/components/Select/v1/__snapshots__/Select.test.js.snap, src/helpers/CustomPropTypes.js, src/helpers/index.js, src/package.json, src/styleguide/index.html, styleguide.config.js, yarn.lock
Creates a `Select` component to match the designs. It wraps `react-select` package. This is an initial implementation and still needs a few more styles applied.
=> Create Select component

.reaction/scripts/addcomponent.js, .reaction/scripts/templates/index.js.template
=> Add index template file.

README.md, docs/README.md, docs/architecture/decisions/0004-define-project-structure.md, docs/component-development-guidelines.md, docs/creating-new-component-version.md, docs/creating-new-component.md, docs/repo-structure.md, docs/style-guide-development.md
Moved docs out of README and into /docs, and expanded on some missing info.
=> docs: expand and update docs

package/src/components/CartCheckoutButton/v1/CartCheckoutButton.js, package/src/components/CartCheckoutButton/v1/CartCheckoutButton.md, package/src/components/CartCheckoutButton/v1/CartCheckoutButton.test.js, package/src/components/CartCheckoutButton/v1/__snapshots__/CartCheckoutButton.test.js.snap, package/src/components/CartCheckoutButton/v1/index.js, styleguide.config.js
This PR adds a `CartCheckoutButton` component.
This button will allow a user to proceed with checkout when clicked.
=> feat: Cart checkout button

package/src/components/MiniCartSummary/v1/MiniCartSummary.js, package/src/components/MiniCartSummary/v1/MiniCartSummary.md, package/src/components/MiniCartSummary/v1/MiniCartSummary.test.js, package/src/components/MiniCartSummary/v1/__snapshots__/MiniCartSummary.test.js.snap, package/src/components/MiniCartSummary/v1/index.js, styleguide.config.js
Add mini cart summary component as specified here:  https://github.com/reactioncommerce/reaction/issues/4322
=> Add mini cart summary component.

.snyk, package/src/components/CartItem/v1/CartItem.js, package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap, package/src/components/CartItemDetail/v1/CartItemDetail.js, package/src/components/CartItemDetail/v1/__snapshots__/CartItemDetail.test.js.snap, package/src/components/CartItems/v1/CartItems.js, package/src/components/CartItems/v1/CartItems.md, package/src/components/CartItems/v1/CartItems.test.js, package/src/components/CartItems/v1/__snapshots__/CartItems.test.js.snap, package/src/components/CartItems/v1/index.js, package/src/components/Price/v1/Price.js, package/src/components/Price/v1/__snapshots__/Price.test.js.snap, package/src/components/QuantityInput/v1/QuantityInput.js, package/src/components/QuantityInput/v1/__snapshots__/QuantityInput.test.js.snap, package/src/components/StockWarning/v1/StockWarning.js, package/src/components/StockWarning/v1/__snapshots__/StockWarning.test.js.snap, package/src/defaultComponentTheme.js, styleguide.config.js
Resolves #134  
Added a CartItems component based on these [specs](https://github.com/reactioncommerce/reaction-next-starterkit/issues/134)
Desktop
Mobile
1. Make sure it looks good and works
=> (feat): 134 nnnnat cart items

package/src/components/CartItem/v1/CartItem.md, package/src/components/CartItem/v1/CartItem.test.js, package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap, package/src/components/CartItems/v1/CartItems.md, package/src/components/CartItems/v1/CartItems.test.js, package/src/components/MiniCart/v1/MiniCart.md, package/src/components/MiniCart/v1/MiniCart.test.js
Type: **fix**
Update URL's to use `//` instead of `http` so we can get `https` if needed.
=> fix: use `//` instead of `http` on placeholdit URLs

package/src/components/CheckoutTopHat/v1/CheckoutTopHat.js, package/src/components/CheckoutTopHat/v1/CheckoutTopHat.md, package/src/components/CheckoutTopHat/v1/CheckoutTopHat.test.js, package/src/components/CheckoutTopHat/v1/index.js, styleguide.config.js, styleguide/src/sections/Checkout.md
Resolves #106 
CheckoutTopHat component will display at the top of the checkout page, if a message is provided to it. If no message is provided, it will not show.
None
See that the TopHat component matches [designs](https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f4fa90d3b184213318da). See that it does not render if no message is displayed.
=> feat: CheckoutTopHat component

README.md
=> docs: add Netlify URL to README

package/src/components/CartItem/v1/CartItem.js, package/src/components/CartItem/v1/CartItem.md, package/src/components/CartItem/v1/CartItem.test.js, package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap, package/src/components/CartItemDetail/v1/CartItemDetail.js, package/src/components/CartItemDetail/v1/CartItemDetail.md, package/src/components/CartItemDetail/v1/CartItemDetail.test.js, package/src/components/CartItemDetail/v1/__snapshots__/CartItemDetail.test.js.snap, package/src/components/CartItems/v1/CartItems.js, package/src/components/CartItems/v1/CartItems.md, package/src/components/CartItems/v1/CartItems.test.js, package/src/components/MiniCart/v1/MiniCart.js, package/src/components/MiniCart/v1/MiniCart.md, package/src/components/MiniCart/v1/MiniCart.test.js
- CartItem
- CartItems
- CartItemDetail
No visual changes. Everything should look the same.
None
Verify that the listed components still look and function correct.
=> fix: update CartItem props to match GraphQL schema changes

docs/README.md, docs/browser-compatibility.md
Resolves #156 
Type: **docs**
Document our browser compatibility requirement list, based on React 16's
Tagging you @jeffcorpuz cos I wanted you to be in the loop about this! We decided on this at the last Frontend Weekly meeting and now we're officially documenting it 💯
=> docs(#156): add browser list, based on React 16's

package/package.json, package/src/components/Select/v1/Select.test.js, package/src/components/Select/v1/__snapshots__/Select.test.js.snap, package/yarn.lock
Update to the now-released stable 2.0.0 version of `react-select` package. Update tests to pass because the HTML has changed a bit behind the scenes.
None
Just make sure our Select component still works.
=> feat: update to react-select@2.0.0

package/src/components/CheckoutTopHat/v1/CheckoutTopHat.js, package/src/components/CheckoutTopHat/v1/__snapshots__/CheckoutTopHat.test.js.snap
Resolves: None
Impact: minor
Type: fix
Small fix to add spacing above and below checkout top hat.
=> fix: add above and below CheckoutTopHat title

package.json, package/src/components/MiniCartSummary/v1/__snapshots__/MiniCartSummary.test.js.snap, yarn.lock
Updated react and react-dom deps to 16.4.2
=> chore: updated react & react-dom dep

package/src/components/PhoneNumberInput/v1/PhoneNumberInput.md
Please use this Markdown template for docs 👍 )
```### Overview
```
=> docs: update PhoneNumberInput docs layout

package/src/components/Button/v1/Button.md, package/src/components/SelectableItem/v1/SelectableItem.js, package/src/components/SelectableItem/v1/SelectableItem.md, package/src/components/SelectableItem/v1/SelectableItem.test.js, package/src/components/SelectableItem/v1/__snapshots__/SelectableItem.test.js.snap, package/src/components/SelectableItem/v1/index.js, package/src/defaultComponentTheme.js, styleguide.config.js
Resolves #149
- `SelectableItem`
- https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f47216618fd82ceea667
- https://app.zeplin.io/project/59305ed4ac6e641b8ea32f76/screen/5a973b288add57e956525370
1. https://deploy-preview-200--stoic-hodgkin-c0179e.netlify.com/#!/SelectableItem
=> feat(#149): SelectableItem

package/src/components/GuestForm/v1/GuestForm.js, package/src/components/GuestForm/v1/GuestForm.md, package/src/components/GuestForm/v1/GuestForm.test.js, package/src/components/GuestForm/v1/__snapshots__/GuestForm.test.js.snap, package/src/components/GuestForm/v1/index.js, styleguide.config.js
Resolves 225 in [starterkit](https://github.com/reactioncommerce/reaction-next-starterkit/issues/225)
Created a `GuestForm` component using reacto-form and the RC form element components. This form only captures a users email address and will be used inside the checkout's login view.
**Desktop**
**Mobile**
1. Verify it looks and works as expected
=> (feat): nnnnat guest form

package/src/components/BadgeOverlay/v1/BadgeOverlay.js, package/src/components/BadgeOverlay/v1/utils/badgeLabels.js, package/src/components/BadgeOverlay/v1/utils/badgeLabels.test.js, package/src/components/BadgeOverlay/v1/utils/badgeStatus.js, package/src/components/BadgeOverlay/v1/utils/badgeStatus.test.js, package/src/components/CatalogGrid/v1/CatalogGrid.js, package/src/components/CatalogGrid/v1/CatalogGrid.md, package/src/components/CatalogGrid/v1/CatalogGrid.test.js, package/src/components/CatalogGrid/v1/__snapshots__/CatalogGrid.test.js.snap, package/src/components/CatalogGridItem/v1/CatalogGridItem.js
Resolves #269 
This PR adds the ability to customize labels for the `BadgeOverlay` component
None
1. Review `CatalogGrid` example with custom badge labels
=> feat: customizable badge labels

package/src/components/ViewerInfo/v1/ViewerInfo.js, package/src/components/ViewerInfo/v1/ViewerInfo.md, package/src/components/ViewerInfo/v1/ViewerInfo.test.js, package/src/components/ViewerInfo/v1/__snapshots__/ViewerInfo.test.js.snap, package/src/components/ViewerInfo/v1/index.js, package/src/defaultComponentTheme.js, styleguide.config.js
Resolves #275 
Impact: Minor
Type: feature
Adds a component to render basic user information
1. Verify implementation matches design
=> feat: add ViewerInfo component

package/src/components/CartItem/v1/CartItem.js, package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap, package/src/components/CatalogGridItem/v1/CatalogGridItem.js
Various design alignment changes.
- decreased line heights
- made vendor text smaller than product title
- decreased horizontal item padding in cart to match design
For: https://github.com/reactioncommerce/reaction-next-starterkit/issues/258
Impact: **minor**
=> Changes for Design Review Epic

package/package.json, package/src/components/QuantityInput/v1/__snapshots__/QuantityInput.test.js.snap, package/yarn.lock
For https://github.com/reactioncommerce/reaction-next-starterkit/issues/291
=> chore(material-ui): update material-ui, mdl-material-ui

package/src/components/CartItem/v1/CartItem.js, package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap, package/src/components/CartSummary/v1/CartSummary.js, package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap, package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.js, package/src/components/FinalReviewCheckoutAction/v1/__snapshots__/FinalReviewCheckoutAction.test.js.snap, package/src/components/MiniCart/v1/MiniCart.js, package/src/components/MiniCart/v1/__snapshots__/MiniCart.test.js.snap, package/src/defaultComponentTheme.js
Resolves #288 
Fixes padding style issue that crept in.
1. Look at MiniCart in its various situations.
=> fix: added padding to MiniCart, only when mini

docs/styling-conventions.md
Resolves #118 
Resolves #205
Type: **docs**
Updates the component style conventions docs.
=> docs: update component style conventions doc

package/src/components/CheckoutActions/v1/CheckoutActions.js
Replaced remaining `action._id` with `action.id` in CheckoutActions component.
=> fix: updated remaining _id to id in CheckoutAction

styleguide/src/sections/InstallingandImporting.md
Type: **docs**
Adding docs for the component that was merged in #318
=> (docs): add ProfileImage to component context docs

package/src/components/AddressBook/v1/AddressBook.js, package/src/components/AddressBook/v1/AddressBook.md, package/src/components/AddressForm/v1/AddressForm.js, package/src/components/AddressForm/v1/AddressForm.md, package/src/components/AddressForm/v1/AddressForm.test.js, package/src/components/AddressForm/v1/__snapshots__/AddressForm.test.js.snap, package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js, package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.md, package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.test.js
AddressBook / AddressForm
None
- See that the Address Book still works correctly now that there is a single `fullName` field instead of separate `firstName` and `lastName` fields
=> refactor: change firstName / lastName to fullName single field

.circleci/config.yml, package.json, package/package.json
LICENSE file was previously updated. I labeled as `feat` to be sure this gets published to NPM on merge as well, and because it seems sort of like a feature.
=> feat: updated NPM license fields to Apache-2.0

package/src/components/CartSummary/v1/CartSummary.js, package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap
impact: **minor**  
Minor copy update on CartSummary
CartSummary
None
1. See that copy is updated
=> chore: update copy and monetary display on surcharge in CartSummary

package/src/components/CartSummary/v1/CartSummary.js
Resolves #issueNumber
Type: **docs**
Comments added, mainly to trigger a version publication so my updates from #389 can be pulled into the starterkit
=> docs: add comments to CartSummary

package/package.json, package/yarn.lock
Material design icons package
none
Ensure the docs still load as expected.
=> chore: update to latest version of the material community icons

package/.snyk
This just ignores some snyk vulnerabilities in the `package` subdir
=> fix: ignores vulnerabilities without upgrade paths

package/scripts/postbuild.js, package/src/components/AddressBook/v1/AddressBook.js, package/src/components/CartSummary/v1/CartSummary.js, package/src/components/CheckoutEmailAddress/v1/CheckoutEmailAddress.js, package/src/components/Field/v1/Field.js, package/src/components/MiniCartSummary/v1/MiniCartSummary.js, package/src/components/StripePaymentInput/v1/StripePaymentInput.js
Resolves un-ticketed linting issues
Fixes linting issues across several components
fix: remove a trailing comma from AddressBook
fix: remove trailing comma from CartSummary
fix: eliminate lint issues CheckoutEmailAddress
fix: eliminate lint issues in Field component
fix: eliminate lint issues in MiniCartSummary
fix: eliminate lint issues in StripePaymentInput
fix: make postbuild recursivelyChangeExt follow consistent-return
=> fix: resolve several linting issues

package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap, package/src/components/GuestForm/v1/__snapshots__/GuestForm.test.js.snap
=> test: update snapshops

package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap, package/src/components/CartItemDetail/v1/__snapshots__/CartItemDetail.test.js.snap, package/src/components/CheckoutActions/v1/CheckoutActions.js
There were some minor lint and outdated test snapshots preventing npm publishing.
=> Fix lint and test errors
